### ISSUE TITLE
Menu item names not in bold in the offline documentation

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#732] opened 2018-03-22 14:17 UTC
In the online documentation the menu item names are written in bold:
https://www.cyberbotics.com/doc/guide/the-user-interface#file-menu

but not in the offline documentation on Linux:
![offline_documentation](https://user-images.githubusercontent.com/5910449/37775721-f9a2009a-2de3-11e8-8686-57df8e6d809a.png)

**Comment by fabienrohrer** [comment] 2018-03-22 14:23
This is also reproducible on macOS Chrome (but not on Firefox).

**Comment by tn12787** [comment] 2018-03-22 14:55
Is this offline in Webots or offline in firefox?

Because if it's offline in Webots there isn't much we can do, it's QtWebKit again...

**Comment by stefaniapedrazzi** [comment] 2018-03-22 15:04
It is in Webots but there is plenty of ways to fix this issue and highlight the menu item names in some ways.
In R2018a it was working.

**Comment by fabienrohrer** [comment] 2018-04-05 07:04
Fixed in https://github.com/omichel/webots-doc/pull/761

**Closed by fabienrohrer** 2018-04-05 07:04 UTC
Labels: incorrect
